HIKERS_PLAYLIST_LINK = "https://open.spotify.com/playlist/6vYqxLulN18MAl9lFzkTV9?si=5563c46ceee44901"
HIKERS_WAIVER_LINK = "https://drive.google.com/file/d/1wqu9yPJ3D7ZCLysH6vXiON0fJQ1Xh2lr/view"
INSTAGRAM_LINK = "https://www.instagram.com/sfuhikers"
STRAVA_PROFILE_LINK = "https://www.strava.com/athletes/144125375"
ICON_URL = "https://go.sfss.ca/clubs/622/logo"